name: Build WeChat & WCPulse from ZIP (Linux + SDK)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git perl clang make fakeroot dpkg unzip curl lzip wget libncurses-dev
          # 安装最新 ldid
          curl -LO https://github.com/theos/ldid/releases/latest/download/ldid_linux_x86_64
          sudo mv ldid_linux_x86_64 /usr/local/bin/ldid
          sudo chmod +x /usr/local/bin/ldid

      - name: Install Theos
        run: |
          git clone --recursive https://github.com/theos/theos.git ~/theos
          echo "THEOS=~/theos" >> $GITHUB_ENV
          echo "$HOME/theos/bin" >> $GITHUB_PATH

      - name: Install iOS SDK
        run: |
          mkdir -p $HOME/theos/sdks
          SDK_URL="https://github.com/theos/sdks/releases/download/16.2/iPhoneOS16.2.sdk.tar.xz"
          SDK_ARCHIVE="iPhoneOS16.2.sdk.tar.xz"
          SDK_DIR="$HOME/theos/sdks/iPhoneOS16.2.sdk"

          if [ ! -d "$SDK_DIR" ]; then
            echo "Downloading SDK..."
            wget -O $SDK_ARCHIVE $SDK_URL
            echo "Extracting SDK..."
            tar -xJf $SDK_ARCHIVE -C $HOME/theos/sdks
          else
            echo "SDK already exists, skipping download."
          fi

      - name: Unzip source files
        run: |
          unzip -o WeChat.zip -d WeChat
          unzip -o "WCPulse源代码.zip" -d WCPulse

      - name: Build WeChat tweak
        working-directory: ./WeChat/WeChat
        run: |
          make package FINALPACKAGE=1 THEOS=$THEOS

      - name: Build WCPulse tweak
        working-directory: ./WCPulse/WCPulse
        run: |
          make package FINALPACKAGE=1 THEOS=$THEOS

      - name: Upload .deb artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Tweaks-deb
          path: |
            WeChat/WeChat/packages/*.deb
            WCPulse/WCPulse/packages/*.deb
